### ISSUE TITLE
Can't connect to X11 window server

### ISSUE THREAD

**Issue by landsman** [marioluan/java-data-structures#24]
Try to run:
```
$ docker-compose up
Recreating java-data-structures_intellij_1 ... done
Starting java-data-structures_gradle_1     ... done
Attaching to java-data-structures_gradle_1, java-data-structures_intellij_1
gradle_1    | Starting a Gradle Daemon, 1 incompatible and 2 stopped Daemons could not be reused, use --status for details
intellij_1  | No protocol specified
intellij_1  | 
intellij_1  | Start Failed: Failed to initialize graphics environment
intellij_1  | 
intellij_1  | java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
intellij_1  | 	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
intellij_1  | 	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
intellij_1  | 	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
intellij_1  | 	at java.security.AccessController.doPrivileged(Native Method)
intellij_1  | 	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
intellij_1  | 	at java.lang.Class.forName0(Native Method)
intellij_1  | 	at java.lang.Class.forName(Class.java:264)
intellij_1  | 	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
intellij_1  | 	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
intellij_1  | 	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:127)
intellij_1  | 	at java.lang.Class.forName0(Native Method)
intellij_1  | 	at java.lang.Class.forName(Class.java:264)
intellij_1  | 	at java.awt.Toolkit$2.run(Toolkit.java:860)
intellij_1  | 	at java.awt.Toolkit$2.run(Toolkit.java:855)
intellij_1  | 	at java.security.AccessController.doPrivileged(Native Method)
intellij_1  | 	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
intellij_1  | 	at java.awt.Toolkit.getEventQueue(Toolkit.java:1736)
intellij_1  | 	at java.awt.EventQueue.isDispatchThread(EventQueue.java:1071)
intellij_1  | 	at javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1361)
intellij_1  | 	at javax.swing.text.StyleContext.reclaim(StyleContext.java:454)
intellij_1  | 	at javax.swing.text.StyleContext.addAttribute(StyleContext.java:311)
intellij_1  | 	at javax.swing.text.html.StyleSheet.addAttribute(StyleSheet.java:578)
intellij_1  | 	at javax.swing.text.StyleContext$NamedStyle.addAttribute(StyleContext.java:1501)
intellij_1  | 	at javax.swing.text.StyleContext$NamedStyle.setName(StyleContext.java:1312)
intellij_1  | 	at javax.swing.text.StyleContext$NamedStyle.<init>(StyleContext.java:1259)
intellij_1  | 	at javax.swing.text.StyleContext.addStyle(StyleContext.java:107)
intellij_1  | 	at javax.swing.text.StyleContext.<init>(StyleContext.java:87)
intellij_1  | 	at javax.swing.text.html.StyleSheet.<init>(StyleSheet.java:166)
intellij_1  | 	at javax.swing.text.html.HTMLEditorKit.getStyleSheet(HTMLEditorKit.java:391)
intellij_1  | 	at com.intellij.util.ui.UIUtil.<clinit>(UIUtil.java:103)
intellij_1  | 	at com.intellij.ide.plugins.PluginManager.start(PluginManager.java:78)
intellij_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
intellij_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
intellij_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
intellij_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
intellij_1  | 	at com.intellij.ide.Bootstrap.main(Bootstrap.java:39)
intellij_1  | 	at com.intellij.idea.Main.main(Main.java:78)
intellij_1  | 
java-data-structures_intellij_1 exited with code 3
gradle_1    | :help
gradle_1    | 
gradle_1    | Welcome to Gradle 4.5.1.
gradle_1    | 
gradle_1    | To run a build, run gradle <task> ...
gradle_1    | 
gradle_1    | To see a list of available tasks, run gradle tasks
gradle_1    | 
gradle_1    | To see a list of command-line options, run gradle --help
gradle_1    | 
gradle_1    | To see more detail about a task, run gradle help --task <task>
gradle_1    | 
gradle_1    | BUILD SUCCESSFUL in 21s
gradle_1    | 1 actionable task: 1 executed
java-data-structures_gradle_1 exited with code 0
```

Output of DISPLAY variable:
```
$ echo $DISPLAY
:0
```

I am using Ubuntu 18.04.
What can be wrong setuped?

**Comment by landsman** [comment]
omg, problem solved by:
`xhost +`

Can I send PR to Readme about this?

**Comment by marioplumbarius** [comment]
Sure.
